---
become_override: false
ocp_username: opentlc-mgr
silent: false

# Helm Chart to deploy
ocp4_workload_mta8_repo: https://github.com/redhat-gpte-devopsautomation/agnosticd_workload_helm_charts.git
# Tag to deploy
ocp4_workload_mta8_repo_tag: main
ocp4_workload_mta8_repo_path: mta8

# Deploy the operator into each user's namespace
ocp4_workload_mta8_deploy_operator: true
# Tackle subscription channel to use
ocp4_workload_mta8_channel: stable-v8.0
ocp4_workload_mta8_starting_csv: ""

# How many users to set up
ocp4_workload_mta8_num_users: 1

# Namespace base
# If num_users == 1 then this will be the name of the namespace
# If num_users > 1 the user base and user number will be appended to this base
ocp4_workload_mta8_namespace_base: mta
# UserID for Single User Setup
ocp4_workload_mta8_user: admin
# Base for multi user setup
ocp4_workload_mta8_user_base: user

# Role to grant users for the tackle namespace
ocp4_workload_mta8_role: admin

# Seed Tackle with information
# When seeding is enabled authentication must be turned off
# (until this is fixed in the operator)
ocp4_workload_mta8_seed: false

# Image for the job to seed tackle. The image must have the data to be seeded inside
# See https://github.com/redhat-gpte-devopsautomation/tackle2-setup-container.git
# Tag should match version of operator channel subscription
# "stable-v2.0" -> "1.0" (legacy tag name)
# "stable-v2.1" -> "v2.1.1" (new matching tag names)
ocp4_workload_mta8_seed_image: quay.io/gpte-devops-automation/tackle2-setup
ocp4_workload_mta8_seed_tag: "release-0.8-mta8"
ocp4_workload_mta8_seed_pull_policy: IfNotPresent

# These are hardcoded and can't be changed at the moment, first login requires changing
# Disable authentication by setting ocp4_workload_mta8_feature_auth_required: false
# ocp4_workload_mta8_user: admin
# ocp4_workload_mta8_password: password

# ArgoCD project to deploy the applications into
ocp4_workload_mta8_user_app_project_prefix: appproject-

# --------------------------------
# Tackle V2 specific settings
# --------------------------------
ocp4_workload_mta8_feature_auth_required: false
ocp4_workload_mta8_maven_data_volume_size: 10Gi
ocp4_workload_mta8_hub_bucket_volume_size: 10Gi
ocp4_workload_mta8_hub_database_volume_size: 5Gi
ocp4_workload_mta8_keycloak_database_data_volume_size: 1Gi
ocp4_workload_mta8_pathfinder_database_data_volume_size: 1Gi
ocp4_workload_mta8_tackle_setup_user: ""
ocp4_workload_mta8_tackle_setup_password: ""
ocp4_workload_mta8_rwx_supported: false

# --------------------------------
# Use a Catalog Snapshot
# --------------------------------
ocp4_workload_mta8_catalogsource_setup: false
ocp4_workload_mta8_catalogsource_name: redhat-operators-snapshot-mta8
ocp4_workload_mta8_catalogsource_image: quay.io/rhpds/olm_snapshot_redhat_catalog
ocp4_workload_mta8_catalogsource_image_tag: v4.15_2024_03_11
